apis:
  - apiFilePath: '../test-artifacts/apis/DynamicClientRegistration/0.2/au-dcr-swagger.yaml'
    sequenceFilePath: '../test-artifacts/apis/DynamicClientRegistration/0.2/au-dcr-insequence-0.2.xml'
    apiProperty:
      check-api-resource: '/register'
      check-dynamic-sequence: 'au-dcr-insequence'
      ob-api-version: '0.2'
    endpointType: 'http'
    sandbox_endpoints: '/api/openbanking/dynamic-client-registration'
    production_endpoints: '/api/openbanking/dynamic-client-registration'
    apiName: 'CDRDynamicClientRegistrationAPI'
    context: '/open-banking/{version}'
    enableSchemaValidation: 'false'
  - apiFilePath: '../test-artifacts/apis/CDSBanking/1.25.0/consumer-data-standards-1.25.0.yaml'
    sequenceFilePath: '../test-artifacts/apis/CDSBanking/1.25.0/cds-api-insequence-1.25.0.xml'
    apiProperty:
      check-api-resource: '/banking/accounts'
      check-dynamic-sequence: 'cds-api-insequence'
      ob-api-version: 'v1'
    endpointType: 'http'
    sandbox_endpoints: '/api/openbanking/cds/backend/services'
    production_endpoints: '/api/openbanking/cds/backend/services'
    apiName: 'ConsumerDataStandards'
    context: '/cds-au/{version}'
    enableSchemaValidation: 'true'
  - apiFilePath: '../test-artifacts/apis/CDSAdminAPIs/1.28.0/consumer-data-standards-admin-1.28.0.yaml'
    sequenceFilePath: '../test-artifacts/apis/CDSAdminAPIs/1.28.0/cds-admin-api-insequence-1.28.0.xml'
    apiProperty:
      check-api-resource: '/register/metadata'
      check-dynamic-sequence: 'cds-admin-api-insequence'
      ob-api-version: 'v1'
    endpointType: 'default'
    apiName: 'ConsumerDataStandardsAdminAPI'
    context: '/cds-au/{version}/admin'
    enableSchemaValidation: 'false'
  - apiFilePath: '../test-artifacts/apis/ArrangementRevocation/cdr-arrangement-mgt-api.yaml'
    sequenceFilePath: ''
    apiProperty:
      check-api-resource: '/revoke'
      check-dynamic-sequence: ''
      ob-api-version: '1.0.0'
    endpointType: 'http'
    sandbox_endpoints: '/api/openbanking/cds-arrangement-revocation/arrangements'
    production_endpoints: '/api/openbanking/cds-arrangement-revocation/arrangements'
    apiName: 'CDRArrangementManagementAPI'
    context: '/arrangements/{version}'
    enableSchemaValidation: 'false'
